### ISSUE TITLE
Migrate to Nextclade v3

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/nextclade_dataset_template#1]
[Migration to Nextclade v3 guide](https://docs.nextstrain.org/projects/nextclade/en/stable/user/migration-v3.html) for reference.

## TODOs

- [ ] update nextalign command in [Snakefile](https://github.com/nextstrain/nextclade_dataset_template/blob/787ce44719fdd14dd8511a7606dd50a68862a50e/Snakefile#L29)
- [ ] update files in [dummy_files](https://github.com/nextstrain/nextclade_dataset_template/tree/main/dummy_files) to match expected v3 dataset files
- [ ] updated [assemble rule's input files](https://github.com/nextstrain/nextclade_dataset_template/blob/787ce44719fdd14dd8511a7606dd50a68862a50e/Snakefile#L161-L168) to match expected v3 dataset files
